name: discloud_config
description: "A configuration file handler to use with Discloud host"
version: 2.3.0

documentation: https://docs.discloud.com/en/discloud.config
homepage: https://discloud.com
issue_tracker: https://github.com/discloud/discloud_config_dart/issues
repository: https://github.com/discloud/discloud_config_dart

topics:
  - discloud
  - parser

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  lints: ^6.1.0
  test: ^1.29.0
